config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }

  enum status: { draft: 0, published: 1, archived: 2 }

  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  
  def self.search(params)
    articles = all # for not existing params args
    if params[:search].present?
      articles = all.where("title like ? OR text LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
    end
    articles
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
     @articles = Article.search(params).paginate(page: params[:page], per_page: 5)
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text, :status, category_ids:[])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='row text-center'>
      <div class='col-md-12'>
        New Article
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <% if @article.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@article.errors.count, "error") %> prohibited
              this article from being saved:
            </h2>
            <ul>
              <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-12'>
        <%= form_with model: @article, local: true do |form| %>
          <table class="table table-borderless">
            <tr>
              <td><%= form.label :title %></td>
              <td><%= form.text_field :title %></td>
            </tr>
            <tr>
              <td><%= form.label :text %></td>
              <td><%= form.text_area :text %></td>
            </tr>
            <tr>
              <td><%= form.label :Status %></td>
              <td><%= form.select :status, options_for_select(Article.statuses.map {|k, v| [k.humanize.capitalize, k]}) %></td>
            </tr>
            <tr>
              <td><%= form.label :Categories %></td>
                <%= form.fields_for(:categories) do |categories| %>
                <td>
                  <select class="form-control select optional select-default select2-hidden-accessible" data-toggle="select" multiple="" name="article[category_ids][]" tabindex="-1" aria-hidden="true">
                  <% Category.all.each do |category, index| %>
                    <option value=<%= category.id %> ><%= category.title.humanize %></option>
                  <% end %>
                  </select>
                </td>
            </tr>
            <% end %>
            <tr>
              <td colspan='2' class='text-center'><%= form.submit %></td>
            </tr>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='row'>
      <div class='col-md-12'>
        <h1 class='text-center'>Listing Articles</h1>
      </div>
    </div>
    <div class='row text-center'>
      <div class='col-md-12'>
        <%= form_tag articles_path, method: :get do %>
          <%= text_field_tag :search, "" %>
          <%= submit_tag 'Search' %>
        <% end %>
      </div>
    </div>
    </br>
    <div class='row'>
      <table class="table table-bordered">
        <tr>
          <th>Id</th>
          <th>Title</th>
          <th>Text</th>
          <th>Status</th>
          <th>Categories</th>
          <th>Action</th>
        </tr>
      
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.id %></td>
            <td><%= article.title %></td>
            <td><%= sanitize(article.text) %></td>
            <td><%= article.status %></td>
            <td><%= article.categories.pluck(:title).join(",") %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class='row'>
      <div class='col-md-12 text-center'>
        <%= will_paginate @articles %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class='row'>
  <div class='col-md-12'>
    <div class='row'>
      <div class='col-md-12'>
        <h1 class='text-center'>Article</h1>
      </div>
    </div>
    </br>
    <div class='row'>
      <table class="table table-bordered">
        <tr>
          <th>Title</th>
          <th>Text</th>
          <th>Status</th>
          <th>Categories</th>
        </tr>
        <tr>
          <td><%= @article.title %></td>
          <td><%= sanitize(@article.text) %></td>
          <td><%= @article.status %></td>
          <td><%= @article.categories.pluck(:title).join(",") %></td>
        </tr>
      </table>
      
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
</br>
<div class='row text-center'>
  <div class='col-md-4'>
    <%= link_to 'Home', articles_path %>
  </div>
  <div class='col-md-4'>
    <%= link_to 'Create New Article', new_article_path %>
  </div>
  <div class='col-md-4'>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
    <% else %>
      <%= link_to('Login', new_user_session_path) %>  
    <% end %>
  </div>
</div>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticleManagmentWithLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render '/layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>